[toolchain]
channel = "stable"
components = [
    "cargo",
    "clippy",
    "miri",
    "rust-doc",
    "rust-src",
    "rust-std",
    "rustc",
    "rustfmt"
]
profile = "default"
targets = [ "wasm32-unknown-unknown", "x86_64-unknown-linux-gnu" ]
